// Code generated by cmd/gift-icongen. DO NOT EDIT.

package solid

import (
	_ "embed"

	"github.com/torbenschinke/gift/ui"
)

// blob is the encoded geometry of all 239 icons of the Flowbite solid set, 56607 bytes.
// Every symbol below is a window into it; no icon owns a slice of its own.
//
//go:embed icons.bin
var blob []byte

// Count is the number of icons in this package.
const Count = 239

// X is X.svg.
var X = ui.NewSymbol(blob[0:110], 24)

// AddressBook is address-book.svg.
var AddressBook = ui.NewSymbol(blob[110:394], 24)

// AdjustmentsHorizontal is adjustments-horizontal.svg.
var AdjustmentsHorizontal = ui.NewSymbol(blob[394:704], 24)

// AdjustmentsVertical is adjustments-vertical.svg.
var AdjustmentsVertical = ui.NewSymbol(blob[704:1014], 24)

// Annotation is annotation.svg.
var Annotation = ui.NewSymbol(blob[1014:1227], 24)

// Apple is apple.svg.
var Apple = ui.NewSymbol(blob[1227:1426], 24)

// ArchiveArrowDown is archive-arrow-down.svg.
var ArchiveArrowDown = ui.NewSymbol(blob[1426:1619], 24)

// Archive is archive.svg.
var Archive = ui.NewSymbol(blob[1619:1769], 24)

// ArrowRightAlt is arrow-right-alt.svg.
var ArrowRightAlt = ui.NewSymbol(blob[1769:1856], 24)

// ArrowUpRightFromSquare is arrow-up-right-from-square.svg.
var ArrowUpRightFromSquare = ui.NewSymbol(blob[1856:2077], 24)

// Award is award.svg.
var Award = ui.NewSymbol(blob[2077:2573], 24)

// BackwardStep is backward-step.svg.
var BackwardStep = ui.NewSymbol(blob[2573:2673], 24)

// BadgeCheck is badge-check.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2294 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var BadgeCheck = ui.NewSymbol(blob[2673:3017], 24)

// BellActiveAlt is bell-active-alt.svg.
var BellActiveAlt = ui.NewSymbol(blob[3017:3311], 24)

// BellActive is bell-active.svg.
var BellActive = ui.NewSymbol(blob[3311:3573], 24)

// BellRing is bell-ring.svg.
var BellRing = ui.NewSymbol(blob[3573:3946], 24)

// Bell is bell.svg.
var Bell = ui.NewSymbol(blob[3946:4108], 24)

// BlenderPhone is blender-phone.svg.
var BlenderPhone = ui.NewSymbol(blob[4108:4459], 24)

// BookOpen is book-open.svg.
var BookOpen = ui.NewSymbol(blob[4459:4586], 24)

// Book is book.svg.
var Book = ui.NewSymbol(blob[4586:4730], 24)

// Bookmark is bookmark.svg.
var Bookmark = ui.NewSymbol(blob[4730:4819], 24)

// Brain is brain.svg.
var Brain = ui.NewSymbol(blob[4819:5214], 24)

// Briefcase is briefcase.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1474 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Briefcase = ui.NewSymbol(blob[5214:5601], 24)

// Bug is bug.svg.
var Bug = ui.NewSymbol(blob[5601:6131], 24)

// Building is building.svg.
var Building = ui.NewSymbol(blob[6131:6519], 24)

// Bullhorn is bullhorn.svg.
var Bullhorn = ui.NewSymbol(blob[6519:6688], 24)

// CalendarEdit is calendar-edit.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (13632 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var CalendarEdit = ui.NewSymbol(blob[6688:7076], 24)

// CalendarMonth is calendar-month.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (942 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var CalendarMonth = ui.NewSymbol(blob[7076:7564], 24)

// CalendarPlus is calendar-plus.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1832 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var CalendarPlus = ui.NewSymbol(blob[7564:7856], 24)

// CalendarWeek is calendar-week.svg.
var CalendarWeek = ui.NewSymbol(blob[7856:8088], 24)

// CameraPhoto is camera-photo.svg.
var CameraPhoto = ui.NewSymbol(blob[8088:8294], 24)

// Caption is caption.svg.
var Caption = ui.NewSymbol(blob[8294:8585], 24)

// CaretDown is caret-down.svg.
var CaretDown = ui.NewSymbol(blob[8585:8651], 24)

// CaretLeft is caret-left.svg.
var CaretLeft = ui.NewSymbol(blob[8651:8717], 24)

// CaretRight is caret-right.svg.
var CaretRight = ui.NewSymbol(blob[8717:8783], 24)

// CaretSort is caret-sort.svg.
var CaretSort = ui.NewSymbol(blob[8783:8911], 24)

// CaretUp is caret-up.svg.
var CaretUp = ui.NewSymbol(blob[8911:8977], 24)

// CartPlusAlt is cart-plus-alt.svg.
var CartPlusAlt = ui.NewSymbol(blob[8977:9306], 24)

// CartPlus is cart-plus.svg.
var CartPlus = ui.NewSymbol(blob[9306:9668], 24)

// Cart is cart.svg.
var Cart = ui.NewSymbol(blob[9668:9850], 24)

// Cash is cash.svg.
var Cash = ui.NewSymbol(blob[9850:10094], 24)

// ChartMixedDollar is chart-mixed-dollar.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2645 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var ChartMixedDollar = ui.NewSymbol(blob[10094:10635], 24)

// ChartPie is chart-pie.svg.
var ChartPie = ui.NewSymbol(blob[10635:10790], 24)

// CheckCircle is check-circle.svg.
var CheckCircle = ui.NewSymbol(blob[10790:10910], 24)

// CheckPlusCircle is check-plus-circle.svg.
var CheckPlusCircle = ui.NewSymbol(blob[10910:11227], 24)

// CircleMinus is circle-minus.svg.
var CircleMinus = ui.NewSymbol(blob[11227:11331], 24)

// CirclePause is circle-pause.svg.
var CirclePause = ui.NewSymbol(blob[11331:11484], 24)

// CirclePlus is circle-plus.svg.
var CirclePlus = ui.NewSymbol(blob[11484:11648], 24)

// ClapperboardPlay is clapperboard-play.svg.
var ClapperboardPlay = ui.NewSymbol(blob[11648:11870], 24)

// ClipboardCheck is clipboard-check.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2026 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var ClipboardCheck = ui.NewSymbol(blob[11870:12098], 24)

// ClipboardClean is clipboard-clean.svg.
var ClipboardClean = ui.NewSymbol(blob[12098:12260], 24)

// ClipboardList is clipboard-list.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1832 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var ClipboardList = ui.NewSymbol(blob[12260:12618], 24)

// Clipboard is clipboard.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1516 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Clipboard = ui.NewSymbol(blob[12618:12880], 24)

// Clock is clock.svg.
var Clock = ui.NewSymbol(blob[12880:12999], 24)

// CloseCircle is close-circle.svg.
var CloseCircle = ui.NewSymbol(blob[12999:13168], 24)

// CloudArrowUp is cloud-arrow-up.svg.
var CloudArrowUp = ui.NewSymbol(blob[13168:13422], 24)

// CodeBranch is code-branch.svg.
var CodeBranch = ui.NewSymbol(blob[13422:13627], 24)

// CodeFork is code-fork.svg.
var CodeFork = ui.NewSymbol(blob[13627:13846], 24)

// CodeMerge is code-merge.svg.
var CodeMerge = ui.NewSymbol(blob[13846:14029], 24)

// CodePullRequest is code-pull-request.svg.
var CodePullRequest = ui.NewSymbol(blob[14029:14280], 24)

// Cog is cog.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (5024 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Cog = ui.NewSymbol(blob[14280:14639], 24)

// Column is column.svg.
var Column = ui.NewSymbol(blob[14639:14753], 24)

// ComputerSpeaker is computer-speaker.svg.
var ComputerSpeaker = ui.NewSymbol(blob[14753:14985], 24)

// CreditCardPlus is credit-card-plus.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1600 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var CreditCardPlus = ui.NewSymbol(blob[14985:15222], 24)

// CreditCard is credit-card.svg.
var CreditCard = ui.NewSymbol(blob[15222:15416], 24)

// Css is css.svg.
var Css = ui.NewSymbol(blob[15416:15528], 24)

// Database is database.svg.
var Database = ui.NewSymbol(blob[15528:15809], 24)

// DesktopPc is desktop-pc.svg.
var DesktopPc = ui.NewSymbol(blob[15809:15961], 24)

// Discord is discord.svg.
var Discord = ui.NewSymbol(blob[15961:16244], 24)

// Download is download.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (316 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Download = ui.NewSymbol(blob[16244:16509], 24)

// DrawSquare is draw-square.svg.
var DrawSquare = ui.NewSymbol(blob[16509:16976], 24)

// Dribbble is dribbble.svg.
var Dribbble = ui.NewSymbol(blob[16976:17351], 24)

// Dropbox is dropbox.svg.
var Dropbox = ui.NewSymbol(blob[17351:17477], 24)

// Edit is edit.svg.
var Edit = ui.NewSymbol(blob[17477:17705], 24)

// EnvelopeOpen is envelope-open.svg.
var EnvelopeOpen = ui.NewSymbol(blob[17705:17818], 24)

// Envelope is envelope.svg.
var Envelope = ui.NewSymbol(blob[17818:17956], 24)

// ExclamationCircle is exclamation-circle.svg.
var ExclamationCircle = ui.NewSymbol(blob[17956:18108], 24)

// EyeSlash is eye-slash.svg.
var EyeSlash = ui.NewSymbol(blob[18108:18431], 24)

// Eye is eye.svg.
var Eye = ui.NewSymbol(blob[18431:18647], 24)

// FaceExplode is face-explode.svg.
var FaceExplode = ui.NewSymbol(blob[18647:19093], 24)

// FaceGrinStars is face-grin-stars.svg.
var FaceGrinStars = ui.NewSymbol(blob[19093:19406], 24)

// FaceGrin is face-grin.svg.
var FaceGrin = ui.NewSymbol(blob[19406:19685], 24)

// FaceLaugh is face-laugh.svg.
var FaceLaugh = ui.NewSymbol(blob[19685:19880], 24)

// Facebook is facebook.svg.
var Facebook = ui.NewSymbol(blob[19880:19969], 24)

// FileChartBar is file-chart-bar.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1516 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileChartBar = ui.NewSymbol(blob[19969:20229], 24)

// FileCheck is file-check.svg.
var FileCheck = ui.NewSymbol(blob[20229:20410], 24)

// FileCirclePlus is file-circle-plus.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1832 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileCirclePlus = ui.NewSymbol(blob[20410:20710], 24)

// FileClone is file-clone.svg.
var FileClone = ui.NewSymbol(blob[20710:20923], 24)

// FileCode is file-code.svg.
var FileCode = ui.NewSymbol(blob[20923:21164], 24)

// FileCopyAlt is file-copy-alt.svg.
var FileCopyAlt = ui.NewSymbol(blob[21164:21352], 24)

// FileCopy is file-copy.svg.
var FileCopy = ui.NewSymbol(blob[21352:21546], 24)

// FileCsv is file-csv.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (6702 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileCsv = ui.NewSymbol(blob[21546:22104], 24)

// FileDoc is file-doc.svg.
var FileDoc = ui.NewSymbol(blob[22104:22547], 24)

// FileExport is file-export.svg.
var FileExport = ui.NewSymbol(blob[22547:22735], 24)

// FileImage is file-image.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (5239 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileImage = ui.NewSymbol(blob[22735:22980], 24)

// FileImport is file-import.svg.
var FileImport = ui.NewSymbol(blob[22980:23158], 24)

// FileInvoice is file-invoice.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (7116 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileInvoice = ui.NewSymbol(blob[23158:23511], 24)

// FileLines is file-lines.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1516 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileLines = ui.NewSymbol(blob[23511:23721], 24)

// FileMusic is file-music.svg.
var FileMusic = ui.NewSymbol(blob[23721:24024], 24)

// FilePaste is file-paste.svg.
var FilePaste = ui.NewSymbol(blob[24024:24318], 24)

// FilePdf is file-pdf.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (7416 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FilePdf = ui.NewSymbol(blob[24318:24778], 24)

// FilePen is file-pen.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1564 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FilePen = ui.NewSymbol(blob[24778:25137], 24)

// FilePpt is file-ppt.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (6644 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FilePpt = ui.NewSymbol(blob[25137:25571], 24)

// FileSearch is file-search.svg.
var FileSearch = ui.NewSymbol(blob[25571:25816], 24)

// FileShield is file-shield.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2206 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FileShield = ui.NewSymbol(blob[25816:26104], 24)

// FileVideo is file-video.svg.
var FileVideo = ui.NewSymbol(blob[26104:26367], 24)

// FileWord is file-word.svg.
var FileWord = ui.NewSymbol(blob[26367:26604], 24)

// FileZip is file-zip.svg.
var FileZip = ui.NewSymbol(blob[26604:26848], 24)

// File is file.svg.
var File = ui.NewSymbol(blob[26848:26958], 24)

// Filter is filter.svg.
var Filter = ui.NewSymbol(blob[26958:27038], 24)

// Fire is fire.svg.
var Fire = ui.NewSymbol(blob[27038:27232], 24)

// Flag is flag.svg.
var Flag = ui.NewSymbol(blob[27232:27385], 24)

// FloppyDiskAlt is floppy-disk-alt.svg.
var FloppyDiskAlt = ui.NewSymbol(blob[27385:27573], 24)

// FloppyDisk is floppy-disk.svg.
var FloppyDisk = ui.NewSymbol(blob[27573:27745], 24)

// Flowbite is flowbite.svg.
var Flowbite = ui.NewSymbol(blob[27745:28269], 24)

// FolderArrowRight is folder-arrow-right.svg.
var FolderArrowRight = ui.NewSymbol(blob[28269:28448], 24)

// FolderDuplicate is folder-duplicate.svg.
var FolderDuplicate = ui.NewSymbol(blob[28448:28652], 24)

// FolderOpen is folder-open.svg.
var FolderOpen = ui.NewSymbol(blob[28652:28764], 24)

// FolderPlus is folder-plus.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2232 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var FolderPlus = ui.NewSymbol(blob[28764:28965], 24)

// Folder is folder.svg.
var Folder = ui.NewSymbol(blob[28965:29055], 24)

// ForwardStep is forward-step.svg.
var ForwardStep = ui.NewSymbol(blob[29055:29155], 24)

// Forward is forward.svg.
var Forward = ui.NewSymbol(blob[29155:29294], 24)

// GiftBox is gift-box.svg.
var GiftBox = ui.NewSymbol(blob[29294:29609], 24)

// Github is github.svg.
var Github = ui.NewSymbol(blob[29609:29925], 24)

// Globe is globe.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (992 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Globe = ui.NewSymbol(blob[29925:30273], 24)

// Google is google.svg.
var Google = ui.NewSymbol(blob[30273:30476], 24)

// GridPlus is grid-plus.svg.
var GridPlus = ui.NewSymbol(blob[30476:30793], 24)

// Grid is grid.svg.
var Grid = ui.NewSymbol(blob[30793:31068], 24)

// Headphones is headphones.svg.
var Headphones = ui.NewSymbol(blob[31068:31234], 24)

// Heart is heart.svg.
var Heart = ui.NewSymbol(blob[31234:31338], 24)

// Home is home.svg.
var Home = ui.NewSymbol(blob[31338:31482], 24)

// Hourglass is hourglass.svg.
var Hourglass = ui.NewSymbol(blob[31482:31692], 24)

// Html is html.svg.
var Html = ui.NewSymbol(blob[31692:31802], 24)

// Image is image.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (10060 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Image = ui.NewSymbol(blob[31802:32004], 24)

// InboxFull is inbox-full.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1516 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var InboxFull = ui.NewSymbol(blob[32004:32263], 24)

// Inbox is inbox.svg.
var Inbox = ui.NewSymbol(blob[32263:32423], 24)

// Indent is indent.svg.
var Indent = ui.NewSymbol(blob[32423:32687], 24)

// InfoCircle is info-circle.svg.
var InfoCircle = ui.NewSymbol(blob[32687:32886], 24)

// Instagram is instagram.svg.
var Instagram = ui.NewSymbol(blob[32886:33170], 24)

// Keyboard is keyboard.svg.
var Keyboard = ui.NewSymbol(blob[33170:33516], 24)

// Label is label.svg.
var Label = ui.NewSymbol(blob[33516:33603], 24)

// Landmark is landmark.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1200 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Landmark = ui.NewSymbol(blob[33603:33865], 24)

// Layers is layers.svg.
var Layers = ui.NewSymbol(blob[33865:34134], 24)

// LifeSaver is life-saver.svg.
var LifeSaver = ui.NewSymbol(blob[34134:34749], 24)

// Lightbulb is lightbulb.svg.
var Lightbulb = ui.NewSymbol(blob[34749:34993], 24)

// Linkedin is linkedin.svg.
var Linkedin = ui.NewSymbol(blob[34993:35162], 24)

// ListMusic is list-music.svg.
var ListMusic = ui.NewSymbol(blob[35162:35454], 24)

// LockOpen is lock-open.svg.
var LockOpen = ui.NewSymbol(blob[35454:35652], 24)

// LockTime is lock-time.svg.
var LockTime = ui.NewSymbol(blob[35652:35920], 24)

// Lock is lock.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2748 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Lock = ui.NewSymbol(blob[35920:36114], 24)

// MailBox is mail-box.svg.
var MailBox = ui.NewSymbol(blob[36114:36374], 24)

// MapPinAlt is map-pin-alt.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2823 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var MapPinAlt = ui.NewSymbol(blob[36374:36568], 24)

// MapPin is map-pin.svg.
var MapPin = ui.NewSymbol(blob[36568:36716], 24)

// Mastercard is mastercard.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2714 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Mastercard = ui.NewSymbol(blob[36716:36974], 24)

// MessageCaption is message-caption.svg.
var MessageCaption = ui.NewSymbol(blob[36974:37267], 24)

// MessageDots is message-dots.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (316 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var MessageDots = ui.NewSymbol(blob[37267:37488], 24)

// Messages is messages.svg.
var Messages = ui.NewSymbol(blob[37488:37682], 24)

// MicrophoneSlash is microphone-slash.svg.
var MicrophoneSlash = ui.NewSymbol(blob[37682:37968], 24)

// Microphone is microphone.svg.
var Microphone = ui.NewSymbol(blob[37968:38212], 24)

// MobilePhone is mobile-phone.svg.
var MobilePhone = ui.NewSymbol(blob[38212:38352], 24)

// Moon is moon.svg.
var Moon = ui.NewSymbol(blob[38352:38475], 24)

// Newspaper is newspaper.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2316 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Newspaper = ui.NewSymbol(blob[38475:38882], 24)

// Npm is npm.svg.
var Npm = ui.NewSymbol(blob[38882:38978], 24)

// ObjectsColumn is objects-column.svg.
var ObjectsColumn = ui.NewSymbol(blob[38978:39246], 24)

// Outdent is outdent.svg.
var Outdent = ui.NewSymbol(blob[39246:39510], 24)

// Palette is palette.svg.
var Palette = ui.NewSymbol(blob[39510:39771], 24)

// PaperPlane is paper-plane.svg.
var PaperPlane = ui.NewSymbol(blob[39771:39869], 24)

// Paragraph is paragraph.svg.
var Paragraph = ui.NewSymbol(blob[39869:39987], 24)

// Pause is pause.svg.
var Pause = ui.NewSymbol(blob[39987:40122], 24)

// PenNib is pen-nib.svg.
var PenNib = ui.NewSymbol(blob[40122:40279], 24)

// Pen is pen.svg.
var Pen = ui.NewSymbol(blob[40279:40438], 24)

// PhoneHangup is phone-hangup.svg.
var PhoneHangup = ui.NewSymbol(blob[40438:40616], 24)

// Phone is phone.svg.
var Phone = ui.NewSymbol(blob[40616:40785], 24)

// Play is play.svg.
var Play = ui.NewSymbol(blob[40785:40851], 24)

// Printer is printer.svg.
var Printer = ui.NewSymbol(blob[40851:41039], 24)

// ProfileCard is profile-card.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (2004 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var ProfileCard = ui.NewSymbol(blob[41039:41411], 24)

// QuestionCircle is question-circle.svg.
var QuestionCircle = ui.NewSymbol(blob[41411:41653], 24)

// Quote is quote.svg.
var Quote = ui.NewSymbol(blob[41653:41862], 24)

// React is react.svg.
var React = ui.NewSymbol(blob[41862:42804], 24)

// Receipt is receipt.svg.
var Receipt = ui.NewSymbol(blob[42804:43118], 24)

// RectangleList is rectangle-list.svg.
var RectangleList = ui.NewSymbol(blob[43118:43479], 24)

// Reddit is reddit.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (8799 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Reddit = ui.NewSymbol(blob[43479:43887], 24)

// ReplyAll is reply-all.svg.
var ReplyAll = ui.NewSymbol(blob[43887:44143], 24)

// Reply is reply.svg.
var Reply = ui.NewSymbol(blob[44143:44289], 24)

// Rocket is rocket.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1248 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Rocket = ui.NewSymbol(blob[44289:44511], 24)

// SalePercent is sale-percent.svg.
var SalePercent = ui.NewSymbol(blob[44511:44928], 24)

// ScaleBalanced is scale-balanced.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (316 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var ScaleBalanced = ui.NewSymbol(blob[44928:45352], 24)

// Search is search.svg.
var Search = ui.NewSymbol(blob[45352:45458], 24)

// Server is server.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (632 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Server = ui.NewSymbol(blob[45458:45776], 24)

// ShareAll is share-all.svg.
var ShareAll = ui.NewSymbol(blob[45776:46032], 24)

// ShareNodes is share-nodes.svg.
var ShareNodes = ui.NewSymbol(blob[46032:46224], 24)

// ShieldCheck is shield-check.svg.
var ShieldCheck = ui.NewSymbol(blob[46224:46388], 24)

// Shield is shield.svg.
var Shield = ui.NewSymbol(blob[46388:46486], 24)

// ShoppingBag is shopping-bag.svg.
var ShoppingBag = ui.NewSymbol(blob[46486:46702], 24)

// Stackoverflow is stackoverflow.svg.
var Stackoverflow = ui.NewSymbol(blob[46702:46872], 24)

// StarHalfStroke is star-half-stroke.svg.
var StarHalfStroke = ui.NewSymbol(blob[46872:47006], 24)

// StarHalf is star-half.svg.
var StarHalf = ui.NewSymbol(blob[47006:47146], 24)

// Star is star.svg.
var Star = ui.NewSymbol(blob[47146:47264], 24)

// Stop is stop.svg.
var Stop = ui.NewSymbol(blob[47264:47334], 24)

// Store is store.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (7824 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Store = ui.NewSymbol(blob[47334:47856], 24)

// Sun is sun.svg.
var Sun = ui.NewSymbol(blob[47856:48311], 24)

// Swatchbook is swatchbook.svg.
var Swatchbook = ui.NewSymbol(blob[48311:48510], 24)

// TableColumn is table-column.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (4200 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var TableColumn = ui.NewSymbol(blob[48510:48623], 24)

// TableRow is table-row.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1400 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var TableRow = ui.NewSymbol(blob[48623:48780], 24)

// Tablet is tablet.svg.
var Tablet = ui.NewSymbol(blob[48780:48900], 24)

// Tag is tag.svg.
var Tag = ui.NewSymbol(blob[48900:49033], 24)

// Tailwind is tailwind.svg.
var Tailwind = ui.NewSymbol(blob[49033:49217], 24)

// Terminal is terminal.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (916 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Terminal = ui.NewSymbol(blob[49217:49395], 24)

// ThumbsDown is thumbs-down.svg.
var ThumbsDown = ui.NewSymbol(blob[49395:49570], 24)

// ThumbsUp is thumbs-up.svg.
var ThumbsUp = ui.NewSymbol(blob[49570:49745], 24)

// Ticket is ticket.svg.
var Ticket = ui.NewSymbol(blob[49745:49903], 24)

// TrashBin is trash-bin.svg.
var TrashBin = ui.NewSymbol(blob[49903:50153], 24)

// Truck is truck.svg.
var Truck = ui.NewSymbol(blob[50153:50448], 24)

// Twitter is twitter.svg.
var Twitter = ui.NewSymbol(blob[50448:50668], 24)

// Upload is upload.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (316 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Upload = ui.NewSymbol(blob[50668:50928], 24)

// UserAdd is user-add.svg.
var UserAdd = ui.NewSymbol(blob[50928:51158], 24)

// UserCircle is user-circle.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (4674 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var UserCircle = ui.NewSymbol(blob[51158:51332], 24)

// UserEdit is user-edit.svg.
var UserEdit = ui.NewSymbol(blob[51332:51568], 24)

// UserHeadset is user-headset.svg.
var UserHeadset = ui.NewSymbol(blob[51568:51866], 24)

// UserRemove is user-remove.svg.
var UserRemove = ui.NewSymbol(blob[51866:52036], 24)

// UserSettings is user-settings.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (1252 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var UserSettings = ui.NewSymbol(blob[52036:52417], 24)

// User is user.svg.
var User = ui.NewSymbol(blob[52417:52537], 24)

// UsersGroup is users-group.svg.
var UsersGroup = ui.NewSymbol(blob[52537:52867], 24)

// Users is users.svg.
var Users = ui.NewSymbol(blob[52867:53115], 24)

// VideoCamera is video-camera.svg.
var VideoCamera = ui.NewSymbol(blob[53115:53237], 24)

// Visa is visa.svg.
var Visa = ui.NewSymbol(blob[53237:53607], 24)

// VolumeDown is volume-down.svg.
var VolumeDown = ui.NewSymbol(blob[53607:53789], 24)

// VolumeMute is volume-mute.svg.
var VolumeMute = ui.NewSymbol(blob[53789:54073], 24)

// VolumeUp is volume-up.svg.
var VolumeUp = ui.NewSymbol(blob[54073:54357], 24)

// Vue is vue.svg.
var Vue = ui.NewSymbol(blob[54357:54429], 24)

// Wallet is wallet.svg.
var Wallet = ui.NewSymbol(blob[54429:54696], 24)

// WandMagicSparkles is wand-magic-sparkles.svg.
var WandMagicSparkles = ui.NewSymbol(blob[54696:55145], 24)

// Whatsapp is whatsapp.svg.
var Whatsapp = ui.NewSymbol(blob[55145:55531], 24)

// WindowRestore is window-restore.svg.
var WindowRestore = ui.NewSymbol(blob[55531:55714], 24)

// Window is window.svg.
// Its fill rule was even-odd and genuinely differs from nonzero (11516 of 57600 samples);
// the contours were reoriented offline so that the hole stays a hole.
var Window = ui.NewSymbol(blob[55714:55950], 24)

// Windows is windows.svg.
var Windows = ui.NewSymbol(blob[55950:56046], 24)

// Youtube is youtube.svg.
var Youtube = ui.NewSymbol(blob[56046:56244], 24)

// ZoomIn is zoom-in.svg.
var ZoomIn = ui.NewSymbol(blob[56244:56456], 24)

// ZoomOut is zoom-out.svg.
var ZoomOut = ui.NewSymbol(blob[56456:56607], 24)
