// Code generated by cmd/gift-icongen. DO NOT EDIT.

package outline

import (
	_ "embed"

	"github.com/worldiety/gift/ui"
)

// blob is the encoded geometry of all 282 icons of the Flowbite outline set, 36398 bytes.
// Every symbol below is a window into it; no icon owns a slice of its own.
//
//go:embed icons.bin
var blob []byte

// Count is the number of icons in this package.
const Count = 282

// AddressBook is address-book.svg.
var AddressBook = ui.NewSymbol(blob[0:192], 24)

// AdjustmentsHorizontal is adjustments-horizontal.svg.
var AdjustmentsHorizontal = ui.NewSymbol(blob[192:401], 24)

// AdjustmentsVertical is adjustments-vertical.svg.
var AdjustmentsVertical = ui.NewSymbol(blob[401:610], 24)

// AlignCenter is align-center.svg.
var AlignCenter = ui.NewSymbol(blob[610:654], 24)

// AngleDown is angle-down.svg.
var AngleDown = ui.NewSymbol(blob[654:677], 24)

// AngleLeft is angle-left.svg.
var AngleLeft = ui.NewSymbol(blob[677:700], 24)

// AngleRight is angle-right.svg.
var AngleRight = ui.NewSymbol(blob[700:723], 24)

// AngleUp is angle-up.svg.
var AngleUp = ui.NewSymbol(blob[723:746], 24)

// Annotation is annotation.svg.
var Annotation = ui.NewSymbol(blob[746:864], 24)

// ArchiveArrowDown is archive-arrow-down.svg.
var ArchiveArrowDown = ui.NewSymbol(blob[864:997], 24)

// Archive is archive.svg.
var Archive = ui.NewSymbol(blob[997:1120], 24)

// ArrowDownToBracket is arrow-down-to-bracket.svg.
var ArrowDownToBracket = ui.NewSymbol(blob[1120:1195], 24)

// ArrowDown is arrow-down.svg.
var ArrowDown = ui.NewSymbol(blob[1195:1231], 24)

// ArrowLeftToBracket is arrow-left-to-bracket.svg.
var ArrowLeftToBracket = ui.NewSymbol(blob[1231:1306], 24)

// ArrowLeft is arrow-left.svg.
var ArrowLeft = ui.NewSymbol(blob[1306:1342], 24)

// ArrowRightAlt is arrow-right-alt.svg.
var ArrowRightAlt = ui.NewSymbol(blob[1342:1384], 24)

// ArrowRightToBracket is arrow-right-to-bracket.svg.
var ArrowRightToBracket = ui.NewSymbol(blob[1384:1459], 24)

// ArrowRight is arrow-right.svg.
var ArrowRight = ui.NewSymbol(blob[1459:1495], 24)

// ArrowSortLetters is arrow-sort-letters.svg.
var ArrowSortLetters = ui.NewSymbol(blob[1495:1573], 24)

// ArrowUpDown is arrow-up-down.svg.
var ArrowUpDown = ui.NewSymbol(blob[1573:1637], 24)

// ArrowUpFromBracket is arrow-up-from-bracket.svg.
var ArrowUpFromBracket = ui.NewSymbol(blob[1637:1712], 24)

// ArrowUpRightDownLeft is arrow-up-right-down-left.svg.
var ArrowUpRightDownLeft = ui.NewSymbol(blob[1712:1770], 24)

// ArrowUpRightFromSquare is arrow-up-right-from-square.svg.
var ArrowUpRightFromSquare = ui.NewSymbol(blob[1770:1864], 24)

// ArrowUp is arrow-up.svg.
var ArrowUp = ui.NewSymbol(blob[1864:1900], 24)

// ArrowsRepeatCount is arrows-repeat-count.svg.
var ArrowsRepeatCount = ui.NewSymbol(blob[1900:1958], 24)

// ArrowsRepeat is arrows-repeat.svg.
var ArrowsRepeat = ui.NewSymbol(blob[1958:2028], 24)

// Atom is atom.svg.
var Atom = ui.NewSymbol(blob[2028:2239], 24)

// Award is award.svg.
var Award = ui.NewSymbol(blob[2239:2561], 24)

// BackwardStep is backward-step.svg.
var BackwardStep = ui.NewSymbol(blob[2561:2598], 24)

// BadgeCheck is badge-check.svg.
var BadgeCheck = ui.NewSymbol(blob[2598:2897], 24)

// Ban is ban.svg.
var Ban = ui.NewSymbol(blob[2897:2965], 24)

// BarsFromLeft is bars-from-left.svg.
var BarsFromLeft = ui.NewSymbol(blob[2965:3000], 24)

// Bars is bars.svg.
var Bars = ui.NewSymbol(blob[3000:3035], 24)

// BellActiveAlt is bell-active-alt.svg.
var BellActiveAlt = ui.NewSymbol(blob[3035:3199], 24)

// BellActive is bell-active.svg.
var BellActive = ui.NewSymbol(blob[3199:3361], 24)

// BellRing is bell-ring.svg.
var BellRing = ui.NewSymbol(blob[3361:3528], 24)

// Bell is bell.svg.
var Bell = ui.NewSymbol(blob[3528:3671], 24)

// BlenderPhone is blender-phone.svg.
var BlenderPhone = ui.NewSymbol(blob[3671:3957], 24)

// BookOpen is book-open.svg.
var BookOpen = ui.NewSymbol(blob[3957:4070], 24)

// Book is book.svg.
var Book = ui.NewSymbol(blob[4070:4164], 24)

// Bookmark is bookmark.svg.
var Bookmark = ui.NewSymbol(blob[4164:4228], 24)

// Brain is brain.svg.
var Brain = ui.NewSymbol(blob[4228:4612], 24)

// Briefcase is briefcase.svg.
var Briefcase = ui.NewSymbol(blob[4612:4782], 24)

// Bug is bug.svg.
var Bug = ui.NewSymbol(blob[4782:5061], 24)

// Building is building.svg.
var Building = ui.NewSymbol(blob[5061:5261], 24)

// Bullhorn is bullhorn.svg.
var Bullhorn = ui.NewSymbol(blob[5261:5406], 24)

// CalendarEdit is calendar-edit.svg.
var CalendarEdit = ui.NewSymbol(blob[5406:5577], 24)

// CalendarMonth is calendar-month.svg.
var CalendarMonth = ui.NewSymbol(blob[5577:5783], 24)

// CalendarPlus is calendar-plus.svg.
var CalendarPlus = ui.NewSymbol(blob[5783:6421], 24)

// CalendarWeek is calendar-week.svg.
var CalendarWeek = ui.NewSymbol(blob[6421:6532], 24)

// CameraPhoto is camera-photo.svg.
var CameraPhoto = ui.NewSymbol(blob[6532:6688], 24)

// Caption is caption.svg.
var Caption = ui.NewSymbol(blob[6688:6836], 24)

// CaretDown is caret-down.svg.
var CaretDown = ui.NewSymbol(blob[6836:6906], 24)

// CaretLeft is caret-left.svg.
var CaretLeft = ui.NewSymbol(blob[6906:6976], 24)

// CaretRight is caret-right.svg.
var CaretRight = ui.NewSymbol(blob[6976:7046], 24)

// CaretSort is caret-sort.svg.
var CaretSort = ui.NewSymbol(blob[7046:7094], 24)

// CaretUp is caret-up.svg.
var CaretUp = ui.NewSymbol(blob[7094:7164], 24)

// CartPlusAlt is cart-plus-alt.svg.
var CartPlusAlt = ui.NewSymbol(blob[7164:7327], 24)

// CartPlus is cart-plus.svg.
var CartPlus = ui.NewSymbol(blob[7327:7498], 24)

// Cart is cart.svg.
var Cart = ui.NewSymbol(blob[7498:7643], 24)

// Cash is cash.svg.
var Cash = ui.NewSymbol(blob[7643:7807], 24)

// ChartLineDown is chart-line-down.svg.
var ChartLineDown = ui.NewSymbol(blob[7807:7872], 24)

// ChartLineUp is chart-line-up.svg.
var ChartLineUp = ui.NewSymbol(blob[7872:7937], 24)

// ChartMixedDollar is chart-mixed-dollar.svg.
var ChartMixedDollar = ui.NewSymbol(blob[7937:8126], 24)

// ChartMixed is chart-mixed.svg.
var ChartMixed = ui.NewSymbol(blob[8126:8190], 24)

// ChartPie is chart-pie.svg.
var ChartPie = ui.NewSymbol(blob[8190:8292], 24)

// Chart is chart.svg.
var Chart = ui.NewSymbol(blob[8292:8347], 24)

// CheckCircle is check-circle.svg.
var CheckCircle = ui.NewSymbol(blob[8347:8420], 24)

// CheckPlusCircle is check-plus-circle.svg.
var CheckPlusCircle = ui.NewSymbol(blob[8420:8498], 24)

// Check is check.svg.
var Check = ui.NewSymbol(blob[8498:8521], 24)

// ChevronDoubleDown is chevron-double-down.svg.
var ChevronDoubleDown = ui.NewSymbol(blob[8521:8559], 24)

// ChevronDoubleLeft is chevron-double-left.svg.
var ChevronDoubleLeft = ui.NewSymbol(blob[8559:8597], 24)

// ChevronDoubleRight is chevron-double-right.svg.
var ChevronDoubleRight = ui.NewSymbol(blob[8597:8635], 24)

// ChevronDoubleUp is chevron-double-up.svg.
var ChevronDoubleUp = ui.NewSymbol(blob[8635:8673], 24)

// ChevronDown is chevron-down.svg.
var ChevronDown = ui.NewSymbol(blob[8673:8696], 24)

// ChevronLeft is chevron-left.svg.
var ChevronLeft = ui.NewSymbol(blob[8696:8719], 24)

// ChevronRight is chevron-right.svg.
var ChevronRight = ui.NewSymbol(blob[8719:8742], 24)

// ChevronSort is chevron-sort.svg.
var ChevronSort = ui.NewSymbol(blob[8742:8779], 24)

// ChevronUp is chevron-up.svg.
var ChevronUp = ui.NewSymbol(blob[8779:8802], 24)

// CircleMinus is circle-minus.svg.
var CircleMinus = ui.NewSymbol(blob[8802:8868], 24)

// CirclePause is circle-pause.svg.
var CirclePause = ui.NewSymbol(blob[8868:8944], 24)

// CirclePlus is circle-plus.svg.
var CirclePlus = ui.NewSymbol(blob[8944:9019], 24)

// ClapperboardPlay is clapperboard-play.svg.
var ClapperboardPlay = ui.NewSymbol(blob[9019:9140], 24)

// ClipboardCheck is clipboard-check.svg.
var ClipboardCheck = ui.NewSymbol(blob[9140:9254], 24)

// ClipboardClean is clipboard-clean.svg.
var ClipboardClean = ui.NewSymbol(blob[9254:9353], 24)

// ClipboardList is clipboard-list.svg.
var ClipboardList = ui.NewSymbol(blob[9353:9484], 24)

// Clipboard is clipboard.svg.
var Clipboard = ui.NewSymbol(blob[9484:9601], 24)

// Clock is clock.svg.
var Clock = ui.NewSymbol(blob[9601:9673], 24)

// CloseCircle is close-circle.svg.
var CloseCircle = ui.NewSymbol(blob[9673:9750], 24)

// Close is close.svg.
var Close = ui.NewSymbol(blob[9750:9777], 24)

// CloudArrowUp is cloud-arrow-up.svg.
var CloudArrowUp = ui.NewSymbol(blob[9777:9909], 24)

// CodeBranch is code-branch.svg.
var CodeBranch = ui.NewSymbol(blob[9909:10103], 24)

// CodeFork is code-fork.svg.
var CodeFork = ui.NewSymbol(blob[10103:10303], 24)

// CodeMerge is code-merge.svg.
var CodeMerge = ui.NewSymbol(blob[10303:10489], 24)

// CodePullRequest is code-pull-request.svg.
var CodePullRequest = ui.NewSymbol(blob[10489:10690], 24)

// Code is code.svg.
var Code = ui.NewSymbol(blob[10690:10737], 24)

// Cog is cog.svg.
var Cog = ui.NewSymbol(blob[10737:11093], 24)

// Column is column.svg.
var Column = ui.NewSymbol(blob[11093:11177], 24)

// Command is command.svg.
var Command = ui.NewSymbol(blob[11177:11402], 24)

// Compress is compress.svg.
var Compress = ui.NewSymbol(blob[11402:11462], 24)

// ComputerSpeaker is computer-speaker.svg.
var ComputerSpeaker = ui.NewSymbol(blob[11462:11598], 24)

// CreditCardPlus is credit-card-plus.svg.
var CreditCardPlus = ui.NewSymbol(blob[11598:11769], 24)

// CreditCard is credit-card.svg.
var CreditCard = ui.NewSymbol(blob[11769:11861], 24)

// Database is database.svg.
var Database = ui.NewSymbol(blob[11861:11998], 24)

// DesktopPc is desktop-pc.svg.
var DesktopPc = ui.NewSymbol(blob[11998:12090], 24)

// Dna is dna.svg.
var Dna = ui.NewSymbol(blob[12090:12217], 24)

// Dollar is dollar.svg.
var Dollar = ui.NewSymbol(blob[12217:12319], 24)

// DotsHorizontal is dots-horizontal.svg.
var DotsHorizontal = ui.NewSymbol(blob[12319:12349], 24)

// DotsVertical is dots-vertical.svg.
var DotsVertical = ui.NewSymbol(blob[12349:12379], 24)

// Download is download.svg.
var Download = ui.NewSymbol(blob[12379:12480], 24)

// DrawSquare is draw-square.svg.
var DrawSquare = ui.NewSymbol(blob[12480:12753], 24)

// Edit is edit.svg.
var Edit = ui.NewSymbol(blob[12753:12881], 24)

// EnvelopeOpen is envelope-open.svg.
var EnvelopeOpen = ui.NewSymbol(blob[12881:12966], 24)

// Envelope is envelope.svg.
var Envelope = ui.NewSymbol(blob[12966:13055], 24)

// Euro is euro.svg.
var Euro = ui.NewSymbol(blob[13055:13130], 24)

// ExclamationCircle is exclamation-circle.svg.
var ExclamationCircle = ui.NewSymbol(blob[13130:13204], 24)

// Expand is expand.svg.
var Expand = ui.NewSymbol(blob[13204:13312], 24)

// EyeSlash is eye-slash.svg.
var EyeSlash = ui.NewSymbol(blob[13312:13440], 24)

// Eye is eye.svg.
var Eye = ui.NewSymbol(blob[13440:13556], 24)

// FaceExplode is face-explode.svg.
var FaceExplode = ui.NewSymbol(blob[13556:13914], 24)

// FaceGrinStars is face-grin-stars.svg.
var FaceGrinStars = ui.NewSymbol(blob[13914:14236], 24)

// FaceGrin is face-grin.svg.
var FaceGrin = ui.NewSymbol(blob[14236:14371], 24)

// FaceLaugh is face-laugh.svg.
var FaceLaugh = ui.NewSymbol(blob[14371:14476], 24)

// FileChartBar is file-chart-bar.svg.
var FileChartBar = ui.NewSymbol(blob[14476:14601], 24)

// FileCheck is file-check.svg.
var FileCheck = ui.NewSymbol(blob[14601:14714], 24)

// FileCirclePlus is file-circle-plus.svg.
var FileCirclePlus = ui.NewSymbol(blob[14714:14868], 24)

// FileClone is file-clone.svg.
var FileClone = ui.NewSymbol(blob[14868:15038], 24)

// FileCode is file-code.svg.
var FileCode = ui.NewSymbol(blob[15038:15166], 24)

// FileCopyAlt is file-copy-alt.svg.
var FileCopyAlt = ui.NewSymbol(blob[15166:15317], 24)

// FileCopy is file-copy.svg.
var FileCopy = ui.NewSymbol(blob[15317:15463], 24)

// FileCsv is file-csv.svg.
var FileCsv = ui.NewSymbol(blob[15463:15693], 24)

// FileDoc is file-doc.svg.
var FileDoc = ui.NewSymbol(blob[15693:15947], 24)

// FileExport is file-export.svg.
var FileExport = ui.NewSymbol(blob[15947:16075], 24)

// FileImage is file-image.svg.
var FileImage = ui.NewSymbol(blob[16075:16305], 24)

// FileImport is file-import.svg.
var FileImport = ui.NewSymbol(blob[16305:16432], 24)

// FileInvoice is file-invoice.svg.
var FileInvoice = ui.NewSymbol(blob[16432:16588], 24)

// FileLines is file-lines.svg.
var FileLines = ui.NewSymbol(blob[16588:16704], 24)

// FileMusic is file-music.svg.
var FileMusic = ui.NewSymbol(blob[16704:16871], 24)

// FilePaste is file-paste.svg.
var FilePaste = ui.NewSymbol(blob[16871:17040], 24)

// FilePdf is file-pdf.svg.
var FilePdf = ui.NewSymbol(blob[17040:17255], 24)

// FilePen is file-pen.svg.
var FilePen = ui.NewSymbol(blob[17255:17422], 24)

// FilePpt is file-ppt.svg.
var FilePpt = ui.NewSymbol(blob[17422:17628], 24)

// FileSearch is file-search.svg.
var FileSearch = ui.NewSymbol(blob[17628:17786], 24)

// FileShield is file-shield.svg.
var FileShield = ui.NewSymbol(blob[17786:17938], 24)

// FileVideo is file-video.svg.
var FileVideo = ui.NewSymbol(blob[17938:18118], 24)

// FileWord is file-word.svg.
var FileWord = ui.NewSymbol(blob[18118:18241], 24)

// FileZip is file-zip.svg.
var FileZip = ui.NewSymbol(blob[18241:18483], 24)

// File is file.svg.
var File = ui.NewSymbol(blob[18483:18581], 24)

// Filter is filter.svg.
var Filter = ui.NewSymbol(blob[18581:18682], 24)

// Fingerprint is fingerprint.svg.
var Fingerprint = ui.NewSymbol(blob[18682:18924], 24)

// Fire is fire.svg.
var Fire = ui.NewSymbol(blob[18924:19058], 24)

// Flag is flag.svg.
var Flag = ui.NewSymbol(blob[19058:19114], 24)

// FloppyDiskAlt is floppy-disk-alt.svg.
var FloppyDiskAlt = ui.NewSymbol(blob[19114:19279], 24)

// FloppyDisk is floppy-disk.svg.
var FloppyDisk = ui.NewSymbol(blob[19279:19435], 24)

// FolderArrowRight is folder-arrow-right.svg.
var FolderArrowRight = ui.NewSymbol(blob[19435:19560], 24)

// FolderDuplicate is folder-duplicate.svg.
var FolderDuplicate = ui.NewSymbol(blob[19560:19724], 24)

// FolderOpen is folder-open.svg.
var FolderOpen = ui.NewSymbol(blob[19724:19814], 24)

// FolderPlus is folder-plus.svg.
var FolderPlus = ui.NewSymbol(blob[19814:19930], 24)

// Folder is folder.svg.
var Folder = ui.NewSymbol(blob[19930:20027], 24)

// ForwardStep is forward-step.svg.
var ForwardStep = ui.NewSymbol(blob[20027:20064], 24)

// Forward is forward.svg.
var Forward = ui.NewSymbol(blob[20064:20161], 24)

// GiftBox is gift-box.svg.
var GiftBox = ui.NewSymbol(blob[20161:20351], 24)

// Globe is globe.svg.
var Globe = ui.NewSymbol(blob[20351:20532], 24)

// GridPlus is grid-plus.svg.
var GridPlus = ui.NewSymbol(blob[20532:20714], 24)

// Grid is grid.svg.
var Grid = ui.NewSymbol(blob[20714:20934], 24)

// Headphones is headphones.svg.
var Headphones = ui.NewSymbol(blob[20934:21063], 24)

// Heart is heart.svg.
var Heart = ui.NewSymbol(blob[21063:21113], 24)

// Home is home.svg.
var Home = ui.NewSymbol(blob[21113:21205], 24)

// Hourglass is hourglass.svg.
var Hourglass = ui.NewSymbol(blob[21205:21322], 24)

// Image is image.svg.
var Image = ui.NewSymbol(blob[21322:21426], 24)

// InboxFull is inbox-full.svg.
var InboxFull = ui.NewSymbol(blob[21426:21555], 24)

// Inbox is inbox.svg.
var Inbox = ui.NewSymbol(blob[21555:21666], 24)

// Indent is indent.svg.
var Indent = ui.NewSymbol(blob[21666:21730], 24)

// InfoCircle is info-circle.svg.
var InfoCircle = ui.NewSymbol(blob[21730:21817], 24)

// Keyboard is keyboard.svg.
var Keyboard = ui.NewSymbol(blob[21817:22127], 24)

// Label is label.svg.
var Label = ui.NewSymbol(blob[22127:22203], 24)

// Landmark is landmark.svg.
var Landmark = ui.NewSymbol(blob[22203:22328], 24)

// Language is language.svg.
var Language = ui.NewSymbol(blob[22328:22436], 24)

// Layers is layers.svg.
var Layers = ui.NewSymbol(blob[22436:22516], 24)

// LetterBold is letter-bold.svg.
var LetterBold = ui.NewSymbol(blob[22516:22625], 24)

// LetterItalic is letter-italic.svg.
var LetterItalic = ui.NewSymbol(blob[22625:22661], 24)

// LetterUnderline is letter-underline.svg.
var LetterUnderline = ui.NewSymbol(blob[22661:22729], 24)

// LifeSaver is life-saver.svg.
var LifeSaver = ui.NewSymbol(blob[22729:23156], 24)

// Lightbulb is lightbulb.svg.
var Lightbulb = ui.NewSymbol(blob[23156:23242], 24)

// Link is link.svg.
var Link = ui.NewSymbol(blob[23242:23359], 24)

// ListMusic is list-music.svg.
var ListMusic = ui.NewSymbol(blob[23359:23463], 24)

// List is list.svg.
var List = ui.NewSymbol(blob[23463:23520], 24)

// LockOpen is lock-open.svg.
var LockOpen = ui.NewSymbol(blob[23520:23629], 24)

// LockTime is lock-time.svg.
var LockTime = ui.NewSymbol(blob[23629:23771], 24)

// Lock is lock.svg.
var Lock = ui.NewSymbol(blob[23771:23880], 24)

// MailBox is mail-box.svg.
var MailBox = ui.NewSymbol(blob[23880:24012], 24)

// MapPinAlt is map-pin-alt.svg.
var MapPinAlt = ui.NewSymbol(blob[24012:24157], 24)

// MapPin is map-pin.svg.
var MapPin = ui.NewSymbol(blob[24157:24238], 24)

// MessageCaption is message-caption.svg.
var MessageCaption = ui.NewSymbol(blob[24238:24381], 24)

// MessageDots is message-dots.svg.
var MessageDots = ui.NewSymbol(blob[24381:24512], 24)

// Messages is messages.svg.
var Messages = ui.NewSymbol(blob[24512:24585], 24)

// MicrophoneSlash is microphone-slash.svg.
var MicrophoneSlash = ui.NewSymbol(blob[24585:25412], 24)

// Microphone is microphone.svg.
var Microphone = ui.NewSymbol(blob[25412:25542], 24)

// Minimize is minimize.svg.
var Minimize = ui.NewSymbol(blob[25542:25650], 24)

// Minus is minus.svg.
var Minus = ui.NewSymbol(blob[25650:25667], 24)

// MobilePhone is mobile-phone.svg.
var MobilePhone = ui.NewSymbol(blob[25667:25759], 24)

// Moon is moon.svg.
var Moon = ui.NewSymbol(blob[25759:25838], 24)

// Newspaper is newspaper.svg.
var Newspaper = ui.NewSymbol(blob[25838:25980], 24)

// ObjectsColumn is objects-column.svg.
var ObjectsColumn = ui.NewSymbol(blob[25980:26220], 24)

// OrderedList is ordered-list.svg.
var OrderedList = ui.NewSymbol(blob[26220:26323], 24)

// Outdent is outdent.svg.
var Outdent = ui.NewSymbol(blob[26323:26387], 24)

// Palette is palette.svg.
var Palette = ui.NewSymbol(blob[26387:26547], 24)

// PaperClip is paper-clip.svg.
var PaperClip = ui.NewSymbol(blob[26547:26642], 24)

// PaperPlane is paper-plane.svg.
var PaperPlane = ui.NewSymbol(blob[26642:26683], 24)

// Paragraph is paragraph.svg.
var Paragraph = ui.NewSymbol(blob[26683:26755], 24)

// Pause is pause.svg.
var Pause = ui.NewSymbol(blob[26755:26878], 24)

// PenNib is pen-nib.svg.
var PenNib = ui.NewSymbol(blob[26878:26958], 24)

// Pen is pen.svg.
var Pen = ui.NewSymbol(blob[26958:27059], 24)

// PhoneHangup is phone-hangup.svg.
var PhoneHangup = ui.NewSymbol(blob[27059:27201], 24)

// Phone is phone.svg.
var Phone = ui.NewSymbol(blob[27201:27344], 24)

// Play is play.svg.
var Play = ui.NewSymbol(blob[27344:27372], 24)

// Plus is plus.svg.
var Plus = ui.NewSymbol(blob[27372:27398], 24)

// Printer is printer.svg.
var Printer = ui.NewSymbol(blob[27398:27547], 24)

// ProfileCard is profile-card.svg.
var ProfileCard = ui.NewSymbol(blob[27547:27719], 24)

// QrCode is qr-code.svg.
var QrCode = ui.NewSymbol(blob[27719:27941], 24)

// QuestionCircle is question-circle.svg.
var QuestionCircle = ui.NewSymbol(blob[27941:28064], 24)

// Quote is quote.svg.
var Quote = ui.NewSymbol(blob[28064:28232], 24)

// Receipt is receipt.svg.
var Receipt = ui.NewSymbol(blob[28232:28341], 24)

// RectangleList is rectangle-list.svg.
var RectangleList = ui.NewSymbol(blob[28341:28456], 24)

// Redo is redo.svg.
var Redo = ui.NewSymbol(blob[28456:28519], 24)

// Refresh is refresh.svg.
var Refresh = ui.NewSymbol(blob[28519:28613], 24)

// ReplyAll is reply-all.svg.
var ReplyAll = ui.NewSymbol(blob[28613:28760], 24)

// Reply is reply.svg.
var Reply = ui.NewSymbol(blob[28760:28887], 24)

// RestoreWindow is restore-window.svg.
var RestoreWindow = ui.NewSymbol(blob[28887:29007], 24)

// Rocket is rocket.svg.
var Rocket = ui.NewSymbol(blob[29007:29216], 24)

// RulerCombined is ruler-combined.svg.
var RulerCombined = ui.NewSymbol(blob[29216:29362], 24)

// SalePercent is sale-percent.svg.
var SalePercent = ui.NewSymbol(blob[29362:29666], 24)

// ScaleBalanced is scale-balanced.svg.
var ScaleBalanced = ui.NewSymbol(blob[29666:29883], 24)

// Search is search.svg.
var Search = ui.NewSymbol(blob[29883:29950], 24)

// Server is server.svg.
var Server = ui.NewSymbol(blob[29950:30101], 24)

// ShareAll is share-all.svg.
var ShareAll = ui.NewSymbol(blob[30101:30248], 24)

// ShareNodes is share-nodes.svg.
var ShareNodes = ui.NewSymbol(blob[30248:30425], 24)

// ShieldCheck is shield-check.svg.
var ShieldCheck = ui.NewSymbol(blob[30425:30514], 24)

// Shield is shield.svg.
var Shield = ui.NewSymbol(blob[30514:30588], 24)

// ShoppingBag is shopping-bag.svg.
var ShoppingBag = ui.NewSymbol(blob[30588:30686], 24)

// Shuffle is shuffle.svg.
var Shuffle = ui.NewSymbol(blob[30686:30776], 24)

// SortHorizontal is sort-horizontal.svg.
var SortHorizontal = ui.NewSymbol(blob[30776:30840], 24)

// Sort is sort.svg.
var Sort = ui.NewSymbol(blob[30840:30904], 24)

// StarHalfStroke is star-half-stroke.svg.
var StarHalfStroke = ui.NewSymbol(blob[30904:31064], 24)

// StarHalf is star-half.svg.
var StarHalf = ui.NewSymbol(blob[31064:31155], 24)

// Star is star.svg.
var Star = ui.NewSymbol(blob[31155:31306], 24)

// Stop is stop.svg.
var Stop = ui.NewSymbol(blob[31306:31372], 24)

// Store is store.svg.
var Store = ui.NewSymbol(blob[31372:31782], 24)

// Sun is sun.svg.
var Sun = ui.NewSymbol(blob[31782:31914], 24)

// Swatchbook is swatchbook.svg.
var Swatchbook = ui.NewSymbol(blob[31914:32102], 24)

// TableColumn is table-column.svg.
var TableColumn = ui.NewSymbol(blob[32102:32184], 24)

// TableRow is table-row.svg.
var TableRow = ui.NewSymbol(blob[32184:32276], 24)

// Tablet is tablet.svg.
var Tablet = ui.NewSymbol(blob[32276:32347], 24)

// Tag is tag.svg.
var Tag = ui.NewSymbol(blob[32347:32439], 24)

// Terminal is terminal.svg.
var Terminal = ui.NewSymbol(blob[32439:32528], 24)

// TextSize is text-size.svg.
var TextSize = ui.NewSymbol(blob[32528:32604], 24)

// TextSlash is text-slash.svg.
var TextSlash = ui.NewSymbol(blob[32604:32677], 24)

// ThumbsDown is thumbs-down.svg.
var ThumbsDown = ui.NewSymbol(blob[32677:32849], 24)

// ThumbsUp is thumbs-up.svg.
var ThumbsUp = ui.NewSymbol(blob[32849:33021], 24)

// Ticket is ticket.svg.
var Ticket = ui.NewSymbol(blob[33021:33139], 24)

// TrashBin is trash-bin.svg.
var TrashBin = ui.NewSymbol(blob[33139:33254], 24)

// Truck is truck.svg.
var Truck = ui.NewSymbol(blob[33254:33457], 24)

// Undo is undo.svg.
var Undo = ui.NewSymbol(blob[33457:33520], 24)

// Upload is upload.svg.
var Upload = ui.NewSymbol(blob[33520:33620], 24)

// UserAdd is user-add.svg.
var UserAdd = ui.NewSymbol(blob[33620:33758], 24)

// UserCircle is user-circle.svg.
var UserCircle = ui.NewSymbol(blob[33758:33920], 24)

// UserEdit is user-edit.svg.
var UserEdit = ui.NewSymbol(blob[33920:34073], 24)

// UserHeadset is user-headset.svg.
var UserHeadset = ui.NewSymbol(blob[34073:34315], 24)

// UserRemove is user-remove.svg.
var UserRemove = ui.NewSymbol(blob[34315:34444], 24)

// UserSettings is user-settings.svg.
var UserSettings = ui.NewSymbol(blob[34444:34678], 24)

// User is user.svg.
var User = ui.NewSymbol(blob[34678:34798], 24)

// UsersGroup is users-group.svg.
var UsersGroup = ui.NewSymbol(blob[34798:35051], 24)

// Users is users.svg.
var Users = ui.NewSymbol(blob[35051:35257], 24)

// VideoCamera is video-camera.svg.
var VideoCamera = ui.NewSymbol(blob[35257:35347], 24)

// VolumeDown is volume-down.svg.
var VolumeDown = ui.NewSymbol(blob[35347:35462], 24)

// VolumeMute is volume-mute.svg.
var VolumeMute = ui.NewSymbol(blob[35462:35617], 24)

// VolumeUp is volume-up.svg.
var VolumeUp = ui.NewSymbol(blob[35617:35761], 24)

// Wallet is wallet.svg.
var Wallet = ui.NewSymbol(blob[35761:35922], 24)

// WandMagicSparkles is wand-magic-sparkles.svg.
var WandMagicSparkles = ui.NewSymbol(blob[35922:36140], 24)

// Window is window.svg.
var Window = ui.NewSymbol(blob[36140:36237], 24)

// ZoomIn is zoom-in.svg.
var ZoomIn = ui.NewSymbol(blob[36237:36322], 24)

// ZoomOut is zoom-out.svg.
var ZoomOut = ui.NewSymbol(blob[36322:36398], 24)
